apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperbeam
  namespace: hypercore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperbeam-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hyperbeam-demo
    spec:
      containers:
      - image: hyperbeam:latest
        #imagePullPolicy: Always
        name: hyperbeam
        ports:
        - name: metrics
          containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/hypercore/function.py
          name: hypercore-function-volume
          readOnly: true
          subPath: function.py
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: hypercore-function
        name: hypercore-function-volume
