apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-snmp
  namespace: newton-ciscos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-metrics
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: telegraf-metrics
    spec:
      containers:
      # TODO: use custom image
      - image: quay.io/dywong/telegraf-cisco:latest
        #imagePullPolicy: Always
        name: telegraf
        ports:
        - name: metrics
          containerPort: 9090
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config-volume
          readOnly: true
          subPath: telegraf.conf
        - mountPath: /usr/share/snmp/mibs/CISCO-PROCESS-MIB.txt
          name: mib1
          readOnly: true
          subPath: CISCO-PROCESS-MIB.txt
        - mountPath: /usr/share/snmp/mibs/CISCO-STP-EXTENSIONS-MIB.txt
          name: mib2
          readOnly: true
          subPath: CISCO-STP-EXTENSIONS-MIB.txt
        - mountPath: /usr/share/snmp/mibs/CISCO-STP-EXTENSIONS-MIB.txt
          name: mib3
          readOnly: true
          subPath: CISCO-STP-EXTENSIONS-MIB.txt
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: telegraf-config
        name: telegraf-config-volume
